<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.electron7</groupId>
  <artifactId>NepaliDateConverterJava</artifactId>
  <packaging>jar</packaging>
  <version>1.0.1</version>
  <name>NepaliDateConverterJava</name>
  <description>Nepali Date Converter written in base Java</description>

  <properties>
   <github.url>https://maven.pkg.github.com/electron7js/NepaliDateConverterJava</github.url>      
   <github.connection>scm:git:https://github.com/electron7js/NepaliDateConverterJava.git</github.connection>
</properties>

  <url>https://github.com/electron7js/NepaliDateConverterJava</url>
<scm>
    <url>${github.connection}</url>
    <connection>${github.connection}</connection>
    <developerConnection>${github.connection}</developerConnection>
</scm>

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
    <developers>
        <developer>
            <id>github</id>
            <name>electron7js</name>
            <url>https://github.com/electron7js</url>
        </developer>
    </developers>

    <distributionManagement>
    <repository>
        <id>github</id>
        <name>GitHub Electron7 Apache Maven Packages</name>
<url>https://maven.pkg.github.com/electron7js/NepaliDateConverterJava</url>
    </repository>

  </distributionManagement>
</project>
